### ISSUE TITLE
bcrypt.go missing ZooWar.com copyright notice

### ISSUE THREAD

**Issue by zoowar** [jameskeane/bcrypt#1]
bcrypt.go contains code derived from https://bitbucket.org/zoowar/bcrypt and requires the following copyright notice.

//
// Copyright 2011 ZooWar.com. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//

**Comment by weekendlogic** [comment]
wow that was quick, I wasn't expecting an issue so soon. 

I have added your copyright notice to the LICENSE file.
